### ISSUE TITLE
pdf.worker.js needed but not that is not clearly stated

### ISSUE THREAD

**Issue by arseneoaa** [jdryg/angular-pdf-viewer#10]
Hello,

Thanks for all this work, I am trying-out your pdf-viewer, it is very good btw.

Just a note, I think the file pdf.worker.js is needed when implementing the pdf viewer (my browser was looking for it and the issue was gone when I added it in /js/libs/) while it was not obvious (for me) that I would need it. Maybe a line in the Readme to remember us that we need it would be helpful.

Thanks again.

**Comment by jdryg** [comment]
Thanks for pointing that out. Added the file in the Dependencies section.
