### ISSUE TITLE
upgrade pdf.js to latest

### ISSUE THREAD

**Issue by jonathanherr** [jdryg/angular-pdf-viewer#11]
Please provide instruction for upgrading to later PDF.js versions, if possible. 

Have you attempted to upgrade to the latest PDF.js? I swapped in 1.3.88 and 1.2.109 but the promises never seemed to fire. Are there changes that need to be made to PDF.js to make it compatible with this codebase?

**Comment by jdryg** [comment]
Unfortunately, I haven't tried to upgrade to the latest PDF.js, yet. I'll try to find some time to test it in the next days. If in the meantime you manage to make it work, you can create a PR and I'll check it out.

**Comment by jdryg** [comment]
I've replaced pdf.js and pdf.worker.js with the 1.2.109 versions (from here https://mozilla.github.io/pdf.js/getting_started/#download) and it seems to work without further modifications. 

If you still have problems please describe what exactly you are doing, what errors you are getting and whether the demo works on your side or not.
